services:
  - type: web
    name: ai-journal-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: MISTRAL_API_KEY
        value: your_api_key_here
      - key: FLASK_ENV
        value: production
