services:
  - type: web
    name: ai-journal-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production